apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ivzbjsthq-go 
  janus-idp.io/tekton: ivzbjsthq-go
  backstage.io/kubernetes-id: ivzbjsthq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ivzbjsthq-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  